print("Step 1: Gadi ka engine start kiya")
print("Step 2: Clutch dabaya aur gear lagaya")
print("step 3: fir clutch chod diya")
print("step 4: fir accelerator liya and gadi badh gye")
print("step 4: fir ek website banaya and chal diya") 
print("please add that")
print("Step 1: Gadi ka engine start kiya")
print("Step 2: Clutch dabaya aur gear lagaya")
print("Step 3: Accelerator diya")
print("Target: 5 saal baad Defender ghar par hai!")
print("engine start kiya")
print("gadi chal padi")
print("Engine start kiya.",end="aur uske turant baad")
print("gadi chal padi")